### PR TITLE
Issue #53: add footer from component library example

### PR DESCRIPTION
**Pull request by alexfinnarn**

### CODE REVIEW

**Comment by tskillern** [comment]
@alexfinnarn because I'm new to GitHub,  I am not sure if I should comment on a PR that is still a work in progress. I can see the deployment, but it also says that draft pull requests cannot be merged. So should I hold off on comments until it's ready?

**Comment by alexfinnarn** [comment]
@tskillern yes. I  put it as a draft to indicate not ready for review. Some styles come from the global styles and not this component so I imagine those will change as the designs are put into code. I'm mainly making sure the links are there and the  footer looks similar to the design derived from the current giving.cu.edu footer, but I'm not paying particular attention to styles.

This where the question of "where the styles meet?" comes into play. I assume most all of the styling will reflect styling in other components/modules instead of being totally unique to the Footer component. I was able to fairly quickly port what I had done already, so that's why I'm doing this now. 

We can either:
- Wait until other styles are in place to go back to the design and match them towards the end of development when styles are more finalized.
- Match the design with completely different style rules. Only becomes a problem if there are many iterations that you then have to style two ways forever...this is probably the worst option.
- Kelly does the footer using the same styling as elsewhere. I have the menu links in a separate file so it is creating the four columns with some unordered lists. I can take the React code, convert to regular HTML elements, merge it in, and then open a "Style the footer" issue for Kelly to work on.
- Kelly does the whole footer however he wants.

..and as far as reviews go, in the right-hand sidebar, there's a place to add reviewers. I would normally add whoever as a reviewer and that should notify you to review. Looking at a PR right after it gets created isn't ideal since tests might fail or the developer might realize they made a mistake and still be developing...or you need to make a PR to test something out on Heroku review app.

So, ideally the process would be for developers to add reviewers when their work is ready to review. Up to this point on may projects, no one has really reviewed my code, lol, so I'll have to change my process.

Screen Shot 2020-09-23 at 6 38 22 PM

I believe Kelly added you and @duquennoisa to review https://github.com/CUCentralAdvancement/essential-cu/pull/56 so he might be accustomed to doing that as well. On your end, you should see a place to add a review. I just added you two as reviewers to this PR so you can see how that looks in real-time.

**Comment by alexfinnarn** [comment]
@tskillern After discussing with @mattroush , we think the best option is...

> Kelly does the footer using the same styling as elsewhere. I have the menu links in a separate file so it is creating the four columns with some unordered lists. I can take the React code, convert to regular HTML elements, merge it in, and then open a "Style the footer" issue for Kelly to work on.

I will take out `theme-ui` and the other dependencies and replace them with basic, unstyled HTML along with the menu links. 

We were discussing how the header doesn't match the giving.cu.edu site so does the footer need to? At least with the links that all go to giving.cu.edu which is styled differently. Links can stay the same, but it might make sense to make them "impact report specific".

**Comment by duquennoisa** [comment]
@alexfinnarn does this mean the button can the the same as the buttons used in the header? (rounded)

**Pull request merged**
