### PR TITLE
Create ir20_content_editor.md

### PR DESCRIPTION
**Pull request by alexfinnarn**

### CODE REVIEW

**Comment by tskillern** [comment]
@alexfinnarn I entered one story. Works well so far. Can we get Melanie and Anne access, too, so they can test? They'll be doing the bulk of the content editing and entry.

**Comment by alexfinnarn** [comment]
@tskillern sure. I used your GitHub username and CU email. What are the suggested usernames? I have CU email addresses, but Melanie isn't on here to use her GH username.

**Comment by tskillern** [comment]
msidwell

duquennoisa

**Comment by tskillern** [comment]
@alexfinnarn Should we still hold off before add any additional stories using the CMS?

**Comment by alexfinnarn** [comment]
@tskillern It is probably fine to use the CMS. No data was lost and revisions are turned on so that mitigates any database loss. 

I didn't do anything cause I had to move stuff, but all I plan to do is save the Cloudinary URI in the Drupal database instead of looking it up each time you edit or load the API response. The contributed module is supposed to have this feature but since it's open source, that code is outdated and no one fixed it yet. There might be an issue with a patch and fix. 

You will easily be able to tell if the network connections are off since the loading the story edit page will white screen if there are images already saved, and if on a new story add page, it'll look like an image is uploading but won't come up with the thumbnail. I plan to write code that catches the error and gives you a nice error message rather than white screening. 

Eventually, I'd like to have something like https://status.cloudinary.com/ which you could subscribe to if a service Digital Engagement manages has an issue and you get updates on the resolution...but completing any kind of service monitoring like that status page will take some time.

**Comment by tskillern** [comment]
Thanks @alexfinnarn We'll start putting stories in. Here's the order that Melanie and I will tackle some of this today: 

1. Photo edit/selection
2. Input text elements in CMS
3. Input photos (if time today -- that'll be the last step)

**Pull request merged**
