### PR TITLE
Add UTM querystrings to Story social share buttons. Remove temp inter…

### PR DESCRIPTION
**Pull request by kmackvolt**
**Add UTM querystrings to Story social share buttons** per https://github.com/CUCentralAdvancement/essential-cu/issues/62

Remove visible temp interest/priority/campus tags from Story Cards - add data-X HTML attributes for testing instead.

### CODE REVIEW

**Comment by kmackvolt** [comment]
Note that all sharing URLs are hard coded to https://essential.cu.edu/.. so code would need to be deployed there to actually test.

**Comment by tskillern** [comment]
Looking at the deployment, I'm fine with the visible tags being removed and getting the social sharing tested on prod. Unless there are objections, should I merge this? @mattroush @kreynen @alexfinnarn

**Comment by mattroush** [comment]
@kmackvolt @tskillern @pspaeth The share links with utm codes look good to me. @kreynen if you want to validate, as well, you can. Otherwise, I think we're good to merge and promote all to production.

**Comment by tskillern** [comment]
@mattroush I have one last minor fix I'd like @kmackvolt to make to financials before pushing to prod, if OK. I'm opening up the issue now and am confirming with Anne as I type. 

@kreynen @pspaeth

**Comment by tskillern** [comment]
I just added the issue that contains the minor fix: https://github.com/CUCentralAdvancement/essential-cu/issues/118

I have no issue pushing to production now. 

@kmackvolt @kreynen @mattroush @pspaeth

**Comment by tskillern** [comment]
Now that https://github.com/CUCentralAdvancement/essential-cu/pull/119 has been merged, I don't need anything further if you decide to push this to production.

**Review by tskillern — APPROVED** [review]

**Pull request merged**
