### PR TITLE
Feature/home financial

### PR DESCRIPTION
**Pull request by kmackvolt**
Using the **react-cookie** package to deal with cookies. 
CSS class to reorder Home page Financials module set in React Effect hook within HomeFinancials component.

Vertical spacing around Home page Financials module adjusted for both conditions.

Tagging @pspaeth for visibility.

### CODE REVIEW

**Review by alexfinnarn — APPROVED** [review]

**Comment by tskillern** [comment]
@kmackvolt is there something I can do to trigger this to see it? 

>  CSS class to reorder Home page Financials module set in React Effect hook within HomeFinancials component.

**Comment by kmackvolt** [comment]
> @kmackvolt is there something I can do to trigger this to see it?
> 
> > CSS class to reorder Home page Financials module set in React Effect hook within HomeFinancials component.
@tskillern 
Ok, here is the deployment URL:
https://essential-cu-feature-ho-im1eat.herokuapp.com/impact-reports/onward

**To trigger the Financials entry condition**, you would need to manually add a cookie. 
While viewing that page, open up the browser inspector / dev tools.
View the Console tab.
Enter this to set a cookie:
`document.cookie="STYXKEY-Interest=financials";`
Refresh the page, and you should see the Financials module above the Story Cards instead of below.
In the Application panel of the browser inspector you can view cookies to make sure it's set, and delete it to reset and start over.

**Comment by duquennoisa** [comment]
@kmackvolt and @tskillern 
I just tested the reordering on the HP for the financials module and its worked both on firefox and chrome. 
I did notice some errors in firefox, not sure what they meant-- I suspect its related to my adblocker? 

image

**Comment by kmackvolt** [comment]
> @kmackvolt and @tskillern
> I just tested the reordering on the HP for the financials module and its worked both on firefox and chrome.
> I did notice some errors in firefox, not sure what they meant-- I suspect its related to my adblocker?
> 
> image

The Uncaught promise errors are coming from the Link components used on all internal links. The errors only occur in Firefox.
Other people have the same error, per googling "nextjs firefox Link uncaught in promise error" but I haven't seen a fix.
Considering it isn't actually causing a problem (the links work), I don't think we need to worry about it.

**Pull request merged**
