### PR TITLE
Feature/story

### PR DESCRIPTION
**Pull request by kmackvolt**
Story page complete except for interest_tag-based highlight colors for related story cards at bottom. 
Tags are displayed on related story card for development WIP purposes; will be deleted later.
Storycard element may be turned into component later on if it's able to be reused on home/story cards module; unsure if it will be at this point. HTML structure and styling will be consistent at the least, hence why the same content is built out on the index.js page for styling purposes.

### CODE REVIEW

**Comment by kmackvolt** [comment]
@tskillern **A few notes on the story page for when you get to the visual review of the preview environment:**

1. **The static Subtitle field** as used on the story page title and in the story cards desktop view has a LOT of text content in it as you will notice. I developed using a shorter static text string that's more realistic in length to make sure it functions as designed. With longer text, the hover effect on the story cards makes the whole thing jump and look goofy; it will look as intended (per the example provided in req doc) with shorter subtitle text.
2. The **social sharing** functionality is hardcoded to the **staging site** URL; so images and other opengraph tag info the social share functionality is looking for won't come through until this branch is pushed to the staging site.
3. The requirements doc said you want **images to appear interspersed throughout the story body text**. But in the data provided those are 2 separate things; so the body text appears, and then any images (with captions) come after. If you do want images in the body, the CMS and data response would need to provide that accordingly and I'll need to rework the front end styling accordingly.

**Comment by tskillern** [comment]
@alexfinnarn Before merging, can we see a story example with more accurate word/character counts and image sizes? It's hard to review Kelly's work appropriately without them. I have a lot of stories ready to approximate the actual data.

**Comment by tskillern** [comment]
@kmackvolt Thank you. 

RE 1. I've asked @alexfinnarn for assistance in our providing more "accurate" content. We actually have a lot of real content ready (though not fully completed) that we can use to better simulate all story-page elements. Whether that can come through the CMS at this point or needs to be supplied in the data file, I don't know. 

RE 2. Understood. I will take a look on staging.

RE 3. @alexfinnarn Kelly says the data provided does not account for images alternating with text within the body text area (e.g.: text, image, text, image, etc.) as specified in the requirements, so he's just putting images at the very end of the text. How can we adjust for this need in the data coming through? Do we need to wait for the CMS?

**Comment by tskillern** [comment]
@kmackvolt I've asked @duquennoisa to review this PR as soon as she can Monday morning and offer her thoughts. Even though some of the stories have text lengths that do not reflect what they will be with real content, I think you provided enough examples of stories so that I can compare across stories to see if I can merge. And then I will know follow-up issues we might have. I see now there are branch conflicts that need to be resolved, however, before we can do that.

**Comment by alexfinnarn** [comment]
There is now a `yarn.lock` conflict, which isn't that important but has to be resolved, and @duquennoisa , I've shortened the subtitle on https://essential-cu-feature-st-2gvkws.herokuapp.com/impact-reports/onward. I made them randomly between 60 and 80 characters as that's what the subtitles look to be as currently written. 

I also updated the data layer in another issue and placed images in the WYSIWYG here: https://essential-cu-feature-65-ayasda.herokuapp.com/impact-reports/onward This removes the extra images in lieu of them being in the WYSIWYG content. It also has a couple of block quotes. I'll explain the content entry side of this but I think it will be the final structure of data, and and can be used for actual content entry.

**Review by alexfinnarn — APPROVED** [review]

**Comment by alexfinnarn** [comment]
@kmackvolt and @duquennoisa The only difference in this branch and the one I linked to that made https://essential-cu-feature-st-2gvkws.herokuapp.com/impact-reports/onward 

...is this small code change https://github.com/CUCentralAdvancement/essential-cu/pull/73. I don't want to automatically merge code into someone else's branch so I left it at this PR and that example site with the small code change.

**Comment by kmackvolt** [comment]
@alexfinnarn This branch is updated with changes from **master** and yarn.lock conflict is resolved.

**Comment by tskillern** [comment]
@kmackvolt This looks good. I'll make some notes about a few things that I will mention in an issue.

**Pull request merged**
