### PR TITLE
Feature/home storycards

### PR DESCRIPTION
**Pull request by kmackvolt**
This PR covers a number of things:

1. **Cookie reading and sort logic for the home page story cards.** Stories are first sorted by priority order. If a campus cookie is found, those stories are sorted to the front.
To test, enter this (or a Boulder, Denver, Anschutz variation) in a console window:
`document.cookie="STYXKEY-Campus=UCCS";`
View the Application tab to delete or view cookies.
The small textbox that displays the priority # and tags is still present, for easy testing.
2. More completed opengraph tags for the home page and story pages for social sharing, some changed after previous data layer PR.
3. **Story page image and caption handling.** The way images are provided in the story page data changed after the previous data layer PR. They are no longer at the end of each story; they are now inline within the page body text. I am doing some fairly specific string parsing to extract each image, wrap the necessary HTML containers around it, duplicate the ALT text as a caption, and insert that into the story body text for rendering.
4. Added some focus outlines to elements on the home page that were missing it, for accessibility.
5. Some misc cleanup (deleting the styleguide page).

On the Story page, there are now **blockquote** elements coming through. These do not have any special styling currently, beyond the default HTML indenting. LMK if you want to style those differently.

Also, I noticed in the text rendered in the story body that often there are a large number of &nbsp; (non-breaking space) special characters where there should be regular spaces. These will prevent text from wrapping. If you find text is wrapping oddly in places, that content should be edited and &nbsp; replaced with regular spaces. This probably comes from pasting in content from other sources (like MS Word) without sanitizing it first in a basic text editor. I could also parse the text and remove those if it's an issue.

@pspaeth

### CODE REVIEW

**Review by alexfinnarn — CHANGES_REQUESTED** [review]
Had a paths issue when building the site so I created https://github.com/CUCentralAdvancement/essential-cu/pull/107 to "fix" it although I'm not sure why the `/impact-reports/omward/[slug]` path always gets called...haven't looked into it much vs. other priorities.

Parsing failed at the `.replace()` parts of code because those properties didn't exist. Data will be complete by launch but some CMS content doesn't have all the fields filled in. I need to do a better job of this on the API side of things, but it's not at the top of my list.

The deployment link on that PR does seem to parse the body and apply styles. I didn't look at anything else cookie-related or otherwise as I think other people are testing that part.

**Comment by kmackvolt** [comment]
Here is the previewable deployment URL (generated from Alex's #107 mentioned above):
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/impact-reports/onward
@tskillern @duquennoisa @pspaeth

**Comment by kmackvolt** [comment]
..
> Parsing failed at the `.replace()` parts of code because those properties didn't exist. Data will be complete by launch but some CMS content doesn't have all the fields filled in. I need to do a better job of this on the API side of things, but it's not at the top of my list.
....

I just updated the PR to check for the existence of the relevant <img and alt strings before replacing them.

**Comment by kreynen** [comment]
This is working like I'd expect for UCCS...

Screen Shot 2020-10-14 at 8 08 33 AM

But not for UCB or UCD.

Screen Shot 2020-10-14 at 8 09 06 AM


Rather manually settings cookies with the STYXKEY Pantheon prefix, you can use the frontdoor script that sets the Campus and Interest cookies from the utm_content values. This is how the cookie value will be set for all users coming from Marketing Cloud.

https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=UCB_financials
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=UCB
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=UCCS_financials
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=UCCS
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=UCD_financials

It's also helpful to test what happens if the utm_content value isn't something we are expecting...
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=123
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=banana
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=

One thing we noticed earlier was that financials is case sensitive. https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=UCCS_financials works to prioritize the financial module. https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=UCCS_Financials doesn't.

**Comment by tskillern** [comment]
I used URLs that @kreynen provided. 

Eg: https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=UCD_financials

But if I change UCD to "Denver" it works for me. 

https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=Denver_financials

Also working: 

https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=Boulder_financials
https://essential-cu-feature-ho-ocj6x2.herokuapp.com/r/index.html?utm_content=Anschutz_financials

**Comment by kreynen** [comment]
Using the human readable values for campus codes in the cookie is not what was discussed in https://github.com/CUCentralAdvancement/essential-cu/issues/64#issuecomment-697070286 or https://github.com/CUCentralAdvancement/essential-cu/issues/76#issuecomment-702182565. The campus value is stored as the UCB/UCCS/UCD/AMC codes in many systems including Marketing Cloud. 

My guess is the taxonomy in D9 only has a tid/string relationship, but whenever possible we should store and use the official codes like in https://giving.cu.edu/admin/config/people/accounts/fields/field_staff_affiliation. 

I could change value from the campus code to the string when the cookie is set, but then I'd have to convert it back when reporting in other places. The goal is to standardize this.

**Comment by kmackvolt** [comment]
PR updated to check for campus cookie codes **AMC, UCB, UCD, UCCS** (instead of Anschutz, Boulder, Denver, UCCS). **Case insensitivity** for code values and financials cookie value now allowed.

**Comment by tskillern** [comment]
@kmackvolt 

**Re: Cookie reading and sort logic for the home page story cards.**

I have been testing to see what works for sorting. As I noted, it works if I use these values in the URL (Denver, Boulder, UCCS, Anschutz) but not the standard code values that @kreynen mentioned. Beyond these limited tests, I don't know what other circumstances I would test to see cookies continue to work or not. 

**Re: More completed opengraph tags for the home page and story pages for social sharing, some changed after previous data layer PR.**

Twitter is loading a previous placeholder image for a story rather than what is current in the data. See: 

Screen Shot 2020-10-14 at 9 57 05 AM

LinkedIn works as expected. I do not have Facebook so I cannot test. @duquennoisa can you check? 

**Re: duplicate the ALT text as a caption, and insert that into the story body text for rendering.**

We need to use the caption data (not alt tags) for the caption since they are likely to be substantially different. I understand the captions in most instances had no values. I have since asked Melanie to insert captions through the CMS, which she did not know she needed to do. Is this possible >> If the `data-caption` has a value, display it. If `data-caption` doesn't have a value, display nothing. (If all photos need to have captions, we will write them -- but hoping this might be easier.)

**Re: Added some focus outlines to elements on the home page that were missing it, for accessibility.**

The financials module on the home page was discussed internally this morning. Because the button does not outline when tabbing through, it's not clear it's a clickable element. Can we make each of those elements separately clickable/tappable instead of the entire element? (Not sure if this would be caught in QA accessibility testing, so I thought I'd flag now since you mentioned specifically in this PR.)

**Re: On the Story page, there are now blockquote elements coming through. These do not have any special styling currently, beyond the default HTML indenting. LMK if you want to style those differently.**

Nope, looks good as default blockquote tag.

**Re: non-breaking spaces**

We noticed, too, and will clean up on our end. 

@pspaeth

**Comment by duquennoisa** [comment]
@tskillern just checked facebook and its behaving similar to twitter. 
image

**Comment by kmackvolt** [comment]
@tskillern @duquennoisa None of the Opengraph changes are going to work until this branch is merged into master and deployed to the actual staging site, as before. 

I can't quite keep up with what's going on with deployments and where my changes to this PR are being deployed to. 

If you're not seeing the other changes I've recently made, something is off and the URL you are viewing is not reflecting those changes. We need to figure out why the deployment isn't working and it needs to be fixed.

**Comment by tskillern** [comment]
@kmackvolt Understood on social. I recall that from before and should've asked that first. Apologies. 

I am using this URL: https://essential-cu-feature-ho-ocj6x2.herokuapp.com/impact-reports/onward

**Comment by kmackvolt** [comment]
> @kmackvolt Understood on social. I recall that from before and should've asked that first. Apologies.
> 
> I am using this URL: https://essential-cu-feature-ho-ocj6x2.herokuapp.com/impact-reports/onward

That deployment is definitely out of date. Don't review that for any of the recent changes to this PR.

**Comment by kmackvolt** [comment]
@tskillern Ok, here is an up to date deployment URL:
https://essential-cu-feature-ho-7ewrfr.herokuapp.com/impact-reports/onward

**Review by alexfinnarn — APPROVED** [review]

**Comment by tskillern** [comment]
Merging now. Will create an issue to follow up on comments here on 106.

**Comment by kmackvolt** [comment]
@kreynen Can you verify this, as I need to pass this on to our QA team?

**A complete list of simplified URLs to test Financials module reorder and campus tag Story Card sort order would be:**
https://essential.cu.edu/r/index.html?utm_content=UCB_financials
https://essential.cu.edu/r/index.html?utm_content=UCB
https://essential.cu.edu/r/index.html?utm_content=UCCS_financials
https://essential.cu.edu/r/index.html?utm_content=UCCS
https://essential.cu.edu/r/index.html?utm_content=UCD_financials
https://essential.cu.edu/r/index.html?utm_content=AMC
https://essential.cu.edu/r/index.html?utm_content=AMC_financials
https://essential.cu.edu/r/index.html?utm_content=UCD
https://essential.cu.edu/r/index.html?utm_content=UCD_financials


I can't verify myself, as the https://essential.cu.edu/r/index.html site does not have the latest code deployed to it so things are outdated and not working.

**Pull request merged**
